### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by susannakinnunen** [LaihoE/tiralabra#1]
Date and time of project cloning: 15.2.2023 at 9:40

Great work! The code looked good and worked with the example file. The different functionalities were cleverly divided into different modules and classes. The explanations about the files in the implementation document gave a nice understanding of their functionalities.

I found it interesting to have the tables in the interpret_distance and interpret_run_length methods (class Decompress) . The link to the source was great. The source document gave a good overview what the algorithm is about. In my opinion in all of the classes even more explanations about the methods, variables and numbers could be added if possible.
 
I couldn't run the tests with the given instructions. However by reading the test files, it seemed that separate functions were well covered. It was mentioned that end to end will be tested when deflate is done which is very understandable. Maybe the test_huffman_block -test could be already tried with a longer string? Is it possible to get a larger compressed text file to give as a parameter for the Decompressor? You could  save the string from the original file and convert it with bytes() in order to compare the similarity.

I am too working with Huffman Coding (later also with LZ77), however to understand deflate so comprehensively that I could give feedback about the functionalities of your code is difficult with the time given for this course. I am sorry for that!

Overall, good work!

**Comment by LaihoE** [comment]
Thank you for the review. Sorry about the tests, ill try to fix that. Regarding longer tests for the huffman block, I felt that there should not be too much left to implement before it works with all data, so ill just finish it up and then test much longer text at a time.

**Comment by susannakinnunen** [comment]
No worries about the tests and your comment about the huffman block test sounds reasonable!
