### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by JoonasC** [LaihoE/tiralabra#2]
# General
**Code downloaded**: on 26.02 at 20:00
I was able to run the tests. The program works as intended, and I did not notice any bugs. The code is well documented and comprehensively tested.

# Program implementation
The program implementation has one issue, which could be remedied:

In the file that implements huffman tree generation (huffman.py), there are many functions which are outside of the `Huffman` class. In my opinion, these functions could be moved into the `Huffman` class in order to better conform to the object oriented programming paradigm.

Other than this I don't have any other issues with the program implementation, function and variable names are sensible and the code is easy to read. Good work!

# Algorithm implementation
The huffman encoding algorithm is implemented properly, I don't have any particular issues with it.

**Comment by LaihoE** [comment]
Thanks for the review. Yeah you are right about the functions in huffman.py ill try to get them into the class.
